---
- hosts: localhost
  tasks:
  - name: Install yum packages
    yum: name={{ item }}
    with_items:
      - tmux
      - nodejs
      - npm

  - name: Install npm packages
    npm: name=express global=yes
